name: Daily Update Tracker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

env:
  innoextract_version: 1.9
  arch: amd64

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update trackers_all.txt
        shell: pwsh
        run: |
          curl https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/chenjia404/CnTrackersList/master/all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_tracker.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/Tunglies/TrackersList/main/all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/Tunglies/TrackersList/refs/heads/main/all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_combine.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_combine_aria2.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_exclude.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_exclude_aria2.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_tracker.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_tracker_aria2.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/ATaria2_all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/ATline_all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/kn007/patch/refs/heads/master/trackers.list >> trackers_all.txt
          curl https://raw.githubusercontent.com/kkkgo/all-tracker-list/main/trackerslist.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/dr5hx/tracker_merge/master/all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/phiyuki/Tracker/main/main/trackers.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/Sinnar0047/trackerslist/master/trackers_all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/roxio/LongTrackerList/main/2024_Trackers_ALL.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/Sereinfy/TrackersList/main/main/trackers.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/BoxMiao007/Library/main/Trackers/trackers.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/wcj343169893/Trackerslist/main/trackerslist_exclude.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/wcj343169893/Trackerslist/main/trackerslist_combine.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/wcj343169893/Trackerslist/main/trackerslist_tracker.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/jhhd88/trackerslist/refs/heads/master/trackerslist.txt >> trackers_all.txt
          curl https://github.itzmx.com/1265578519/OpenTracker/master/tracker.txt >> trackers_all.txt
          curl https://torrends.to/torrent-tracker-list/?download=latest >> trackers_all.txt
          curl https://download2390.mediafire.com/4clmhb2up6mgbAg73W8O9khMX7aY8w4QBaXHJu5XxADIz6Brz2tdMXdeLUk3XxfvUDrRl-VYeEfJ2SSc1fOe2Xm3VruuR8vEyKnc7xYmwaSBVoPy40faVgPg0wva1iVOSBNSJfX94cTm9BvMU3pT5692_ovSwnX-p5hTgnZ1hlAz/i0cronnuwj5co6n/super+fast+trackers.txt >> trackers_all.txt
          curl https://newtrackon.com/api/stable >> trackers_all.txt
          bash format.sh trackers_all.txt
          sort formatted_trackers.txt | uniq > trackers_all.txt
          rm -rf formatted_trackers.txt

      - name: Test tracker availability
        shell: bash
        run: |
          sudo apt install node-ws -y
          bash test_trackers.sh trackers_all.txt

      - name: Commit and Push changes
        run: |
          echo $(date +'%Y%m%d') > date.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "$(date +'%Y%m%d')"
          git push -v --progress
